spring.application.name=vinamra

# PostgreSQL Database Configuration
# 1. Clean URL (No username or password inside this string!)
spring.datasource.url=jdbc:postgresql://ep-wispy-frost-a1z0qioj-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

# 2. Credentials
spring.datasource.username=neondb_owner
spring.datasource.password=npg_pKarv6MHI7zq

# 3. Driver
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# FastAPI Service URL (Your teammate's local server)
fastapi.service.url=https://ungratuitously-unrhythmic-meagan.ngrok-free.dev
