spring.application.name=vinamra

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_pKarv6MHI7zq@ep-wispy-frost-a1z0qioj-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ALV4jdp3hlkD
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# FastAPI Service URL (Your teammate's local server)
fastapi.service.url= https://ungratuitously-unrhythmic-meagan.ngrok-free.dev/
